name: Hello World Workflow

# This workflow triggers automatically every time you push code to the repository
on: [push]

jobs:
  say-hello:
    # The type of virtual machine the job will run on
    runs-on: ubuntu-latest    
    steps:
      # Step 2: Run a standard bash command to print the message
      - name: Print Hello World
        run: echo "Hello, World!"