name: Tigger 

# This workflow triggers automatically every time you push code to the repository
on: 
# if someone opens PR to main branch
  pull_request:
    types: [opened, reopened]
    branches:
      - 'releases/**'

  # push:  3 tigger on push to main branch
  #   branches:
  #     - main
#workflow_dispatch 2 tigger on manual dispatch
#[push] 1 tigger on push

jobs:
  tigger:    # The type of virtual machine the job will run on  
    runs-on: ubuntu-latest    
    steps:
      # Step 2: Run a standard bash command to print the message
      - name: main branch push
        run: echo "main branch push"








        