name: Contexts demo

# This workflow triggers automatically every time you push code to the repository
on: [push]

env:
  project: "roboshop"
  component: "cartlogue"
  environment: dev

jobs:
  github-context:
    runs-on: ubuntu-latest    
    steps:
      - name: print info 
        run: |
          echo "branch name: ${{ github.ref_name }} "
          echo "event name: ${{ github.event_name }} "

      - name: access env variables
        run: |
          echo "Project: $project"
          echo "Component: $component"
          echo "Environment: $environment"

      - name: print secrets
        run: |
          echo "DB Username: ${{ secrets.DB_username }}"
          echo "DB password: ${{ secrets.DB_password }}"

      - name: print variables
        run: |
          echo "DB URL: ${{ vars.DB_URL }}"    
