name: Contexts demo

# This workflow triggers automatically every time you push code to the repository
on: [push]

jobs:
  github-context:
    runs-on: ubuntu-latest    
    steps:
      - name: print info 
        run: |
          echo "branch name: ${{ github.ref_name }} "
          echo "event name: ${{ github.event_name }} "

